### ISSUE TITLE
agent snapshot package from oss.sonatype.com  not working on Java

### ISSUE THREAD

**Issue by Roiocam** [ScalaConsultants/mesmer#332]
i am using this agent project for my akka application base on Java 1.8

but the 0.5.1 snapshot jar download from sonatype seem like not fat jar, they don't package scala library or typesafe library into it.

so when i tring to agent my Java application, they throw NoClassFound exception when premain method call. 

i could change the build.sbt and repackage the agent jar to fix this issue. but i am thinking it is better way that  releases a fat jar to gain more compatibility ?

<details><summary>this is my `build.sbt`. they work as well for my local machine.</summary>

```scala
lazy val agent = (project in file("agent"))
  .settings(
    name := "mesmer-akka-agent",
    libraryDependencies ++= {
      openTelemetryInstrumentation ++
      akka.map(_ % "provided") ++
      logback ++
      byteBuddy ++
      typesafeConfig ++
      scalatest ++
      akkaTestkit ++
      jackson ++
      slf4jApi ++
      reflection(scalaVersion.value)
    },
    Compile / mainClass := Some("io.scalac.mesmer.agent.Boot"),
    Compile / packageBin / packageOptions := {
      (Compile / packageBin / packageOptions).value.map {
        case MainClass(mainClassName) =>
          ManifestAttributes(List("Premain-Class" -> mainClassName): _*)
        case other => other
      }
    },
    assembly / test            := {},
    assembly / assemblyJarName := "mesmer-akka-agent.jar",
    assembly / assemblyOption ~= { _.withIncludeScala(true) },
    assemblyMergeStrategySettings,
    Test / fork              := true,
    Test / parallelExecution := true,
    Test / testGrouping := ((Test / testGrouping).value flatMap { group =>
      group.tests.map { test =>
        Tests.Group(name = test.name, tests = Seq(test), runPolicy = group.runPolicy)
      }
    }),
    Test / testOnly / testGrouping := (Test / testGrouping).value
  )
  .settings(addArtifact(Compile / assembly / artifact, assembly).settings: _*)
  .dependsOn(core, extension)
```

</details>

but when i publish my  java application on Kubernetes Environment, the agent was not working.  mesmer-agent won't collect any mertics anymore.

I'm new to the Scala languag.  any tips on running this agent on a java program would be greatly appreciated!

Best regards

**Comment by Roiocam** [comment]
> but when i publish my java application on Kubernetes Environment, the agent was not working. mesmer-agent won't collect any mertics anymore.

oops.  It seems that the configuration I used when I published to Kubernetes did not have `akka.actor.typed.extensions` configured.

It works fine on Kubernetes now, but I have to manually build the agent package from source

**Comment by Roiocam** [comment]
> It works fine on Kubernetes now, but I have to manually build the agent package from source

they only export cluster metrics. like this.     :(

```log
# HELP akka_cluster_shard_regions_on_node Amount of reachable nodes
# TYPE akka_cluster_shard_regions_on_node gauge
akka_cluster_shard_regions_on_node{node="akka://application@127.0.0.1:2551",} 1.0 1646038373246
# HELP akka_cluster_reachable_nodes Amount of shard regions on node
# TYPE akka_cluster_reachable_nodes gauge
akka_cluster_reachable_nodes{node="akka://application@127.0.0.1:2551",} 0.0 1646038373246
# HELP akka_cluster_node_down_total Counter for node down events
# TYPE akka_cluster_node_down_total counter
akka_cluster_node_down_total{node="akka://application@127.0.0.1:2551",} 0.0 1646038373246

```

but the metrics more than that.  

<details><summary>when i using IDEA running application with same agent jar, they working  as well</summrary>

```log
# HELP akka_cluster_reachable_nodes Amount of shard regions on node
# TYPE akka_cluster_reachable_nodes gauge
akka_cluster_reachable_nodes{node="akka://application@127.0.0.1:2551",} 0.0 1646038422495
# HELP akka_system_terminated_actors_total Amount of actors terminated measured from Actor System start
# TYPE akka_system_terminated_actors_total counter
akka_system_terminated_actors_total{node="akka://application@127.0.0.1:2551",} 46.0 1646038422495
# HELP akka_actor_mailbox_time_avg Tracks the minimum time of an message in an Actor's mailbox
# TYPE akka_actor_mailbox_time_avg gauge
akka_actor_mailbox_time_avg{actor_path="/system",node="akka://application@127.0.0.1:2551",} 1459.0 1646038422495
# HELP akka_actor_mailbox_time_min Tracks the maximum time of an message in an Actor's mailbox
# TYPE akka_actor_mailbox_time_min gauge
akka_actor_mailbox_time_min{actor_path="/system",node="akka://application@127.0.0.1:2551",} 2.0832292E7 1646038422495
# HELP akka_actor_processing_time_sum Tracks the amount of processed messages
# TYPE akka_actor_processing_time_sum gauge
akka_actor_processing_time_sum{actor_path="/system",node="akka://application@127.0.0.1:2551",} 1635.0 1646038422495
# HELP akka_cluster_node_down_total Counter for node down events
# TYPE akka_cluster_node_down_total counter
akka_cluster_node_down_total{node="akka://application@127.0.0.1:2551",} 0.0 1646038422495
# HELP akka_actor_failed_messages_total Tracks the sum of failed messages in an Actor
# TYPE akka_actor_failed_messages_total counter
akka_actor_failed_messages_total{actor_path="/system",node="akka://application@127.0.0.1:2551",} 0.0 1646038422495
akka_actor_failed_messages_total{actor_path="/user",node="akka://application@127.0.0.1:2551",} 0.0 1646038422495
# HELP akka_actor_mailbox_size Tracks the size of an Actor's mailbox
# TYPE akka_actor_mailbox_size gauge
akka_actor_mailbox_size{actor_path="/system",node="akka://application@127.0.0.1:2551",} 0.0 1646038422495
akka_actor_mailbox_size{actor_path="/user",node="akka://application@127.0.0.1:2551",} 0.0 1646038422495
# HELP akka_actor_received_messages_total Tracks the sum of received messages in an Actor
# TYPE akka_actor_received_messages_total counter
akka_actor_received_messages_total{actor_path="/system",node="akka://application@127.0.0.1:2551",} 1636.0 1646038422495
akka_actor_received_messages_total{actor_path="/user",node="akka://application@127.0.0.1:2551",} 0.0 1646038422495
# HELP akka_actor_processed_messages_total Tracks the sum of processed messages in an Actor
# TYPE akka_actor_processed_messages_total counter
akka_actor_processed_messages_total{actor_path="/system",node="akka://application@127.0.0.1:2551",} 1636.0 1646038422495
akka_actor_processed_messages_total{actor_path="/user",node="akka://application@127.0.0.1:2551",} 0.0 1646038422495
# HELP akka_actor_mailbox_time_sum Tracks the count of messages in an Actor's mailbox
# TYPE akka_actor_mailbox_time_sum gauge
akka_actor_mailbox_time_sum{actor_path="/system",node="akka://application@127.0.0.1:2551",} 2099.0 1646038422495
# HELP akka_cluster_shard_regions_on_node Amount of reachable nodes
# TYPE akka_cluster_shard_regions_on_node gauge
akka_cluster_shard_regions_on_node{node="akka://application@127.0.0.1:2551",} 1.0 1646038422495
# HELP akka_actor_sent_messages_total Tracks the sum of sent messages in an Actor
# TYPE akka_actor_sent_messages_total counter
akka_actor_sent_messages_total{actor_path="/system",node="akka://application@127.0.0.1:2551",} 460.0 1646038422495
akka_actor_sent_messages_total{actor_path="/user",node="akka://application@127.0.0.1:2551",} 0.0 1646038422495
# HELP akka_actor_stashed_total Tracks stash operations on actors
# TYPE akka_actor_stashed_total counter
akka_actor_stashed_total{actor_path="/system",node="akka://application@127.0.0.1:2551",} 23.0 1646038422495
# HELP akka_system_created_actors_total Amount of actors created measured from Actor System start
# TYPE akka_system_created_actors_total counter
akka_system_created_actors_total{node="akka://application@127.0.0.1:2551",} 197.0 1646038422495
# HELP akka_actor_processing_time_max Tracks the sum processing time of an message in an Actor's receive handler
# TYPE akka_actor_processing_time_max gauge
akka_actor_processing_time_max{actor_path="/system",node="akka://application@127.0.0.1:2551",} 2.225551595E9 1646038422495
# HELP akka_actor_mailbox_time_max Tracks the sum time of the messages in an Actor's mailbox
# TYPE akka_actor_mailbox_time_max gauge
akka_actor_mailbox_time_max{actor_path="/system",node="akka://application@127.0.0.1:2551",} 2.0077513713E10 1646038422495
# HELP akka_actor_processing_time_avg Tracks the miminum processing time of an message in an Actor's receive handler
# TYPE akka_actor_processing_time_avg gauge
akka_actor_processing_time_avg{actor_path="/system",node="akka://application@127.0.0.1:2551",} 625.0 1646038422495
# HELP akka_actor_processing_time_min Tracks the maximum processing time of an message in an Actor's receive handler
# TYPE akka_actor_processing_time_min gauge
akka_actor_processing_time_min{actor_path="/system",node="akka://application@127.0.0.1:2551",} 1.9946292E7 1646038422495
# HELP akka_actor_dropped_messages_total Tracks the sum of dropped messages in an Actor
# TYPE akka_actor_dropped_messages_total counter
akka_actor_dropped_messages_total{actor_path="/system",node="akka://application@127.0.0.1:2551",} 0.0 1646038422495

```
</details>

Best regards

**Comment by lgajowy** [comment]
> but the 0.5.1 snapshot jar download from sonatype seem like not fat jar, they don't package scala library or typesafe library into it.

Did you try using 0.5.0 version ([last release](https://mvnrepository.com/artifact/io.scalac/mesmer-akka-agent_2.13/0.5.0))? - 0.5.1 wasn't released (not planned to be) and will probably be skipped. The 0.5.0 should work for you (nothing really changed between 0.5.1 and 0.5.0 besides some minor cleanups). 

> It works fine on Kubernetes now, but I have to manually build the agent package from source

> so when i tring to agent my Java application, they throw NoClassFound exception when premain method call.

Let me know if you still get NoClassFound with 0.5.0.

**Comment by lgajowy** [comment]
Also, where did you get the 0.5.1 snapshots from?

**Comment by Roiocam** [comment]
## To avoid misinformation from other environments. 

### 1. i am using [Lightbend shopping cart service exmaple](https://developer.lightbend.com/docs/akka-platform-guide/microservices-tutorial/projection-grpc-client.html) and follow the [Readme doc](https://github.com/ScalaConsultants/mesmer-akka-agent/tree/v0.5.0). 


<details><summary>There is my step:</summary>

<details><summary>Step 1: add dependency  like this</summary>

```xml
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-exporter-otlp-metrics</artifactId>
            <version>1.7.0-alpha</version>
        </dependency>
        <dependency>
            <groupId>io.scalac</groupId>
            <artifactId>mesmer-akka-extension_${scala.binary.version}</artifactId>
            <version>0.5.0</version>
        </dependency>
```

</details>

<details><summary>Step 2: add this config on `application.conf`</summary>

```conf
akka.actor.typed.extensions= ["io.scalac.mesmer.extension.AkkaMonitoring"]
```

</details>



<details><summary>Step 3: setup the opentelemetry before original main method</summary>

it's mean that  before `    ActorSystem<Void> system = ActorSystem.create(Behaviors.empty(), "ShoppingCartService");`

```java 
    OtlpGrpcMetricExporter metricExporter = OtlpGrpcMetricExporter.getDefault();

    MetricReaderFactory factory =
        PeriodicMetricReader.create(metricExporter, Duration.ofSeconds(1));

    SdkMeterProvider.builder().registerMetricReader(factory).buildAndRegisterGlobal();
```

</details>

<details><summary>Step 4: package the application </summary>

```shell
mvn clean package -DskipTests
```


</details>


<details><summary>Step 5: exec application via agent </summary>

```shell
❯ java -javaagent:/Users/roiocam/Downloads/agent/mesmer-akka-agent.jar -jar target/shopping-cart-service-1.0.jar
```


</details>


</details>


and then i got the stack trace on terminal


```
Exception in thread "main" java.lang.reflect.InvocationTargetExceptionr -jar target/shopping-cart-service-1.0.jar
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NoClassDefFoundError: com/typesafe/config/ConfigFactory
        at io.scalac.mesmer.agent.Boot$.premain(Boot.scala:23)
        at io.scalac.mesmer.agent.Boot.premain(Boot.scala)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: com.typesafe.config.ConfigFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        ... 8 more
FATAL ERROR in native method: processing of -javaagent failed
[1]    70149 abort      java -javaagent:/Users/roiocam/Downloads/agent/mesmer-akka-agent.jar -jar 
```

when i using IDEA run the main method. the JVM won't complain anything. but the logback print those error: 

```log
[2022-03-01 10:39:14,561] [INFO] [akka.cluster.Cluster] [] [ShoppingCartService-akka.actor.default-dispatcher-6] - Cluster Node [akka://ShoppingCartService@127.0.0.1:2551] - No seed nodes found in configuration, relying on Cluster Bootstrap for joining
[2022-03-01 10:39:14,566] [INFO] [akka.cluster.sbr.SplitBrainResolver] [] [ShoppingCartService-akka.actor.default-dispatcher-6] - SBR started. Config: strategy [KeepMajority], stable-after [20 seconds], down-all-when-unstable [15 seconds], selfUniqueAddress [akka://ShoppingCartService@127.0.0.1:2551#-511592655452660114], selfDc [default].
[2022-03-01 10:39:14,951] [ERROR] [akka.actor.typed.ActorSystem] [] [main] - No global configuration found for akka-actor - check if agent is installed.
[2022-03-01 10:39:14,951] [ERROR] [akka.actor.typed.ActorSystem] [] [main] - No global configuration found for akka-actor - check if agent is installed.
[2022-03-01 10:39:14,954] [ERROR] [akka.actor.typed.ActorSystem] [] [main] - No global configuration found for akka-http - check if agent is installed.
[2022-03-01 10:39:14,955] [ERROR] [akka.actor.typed.ActorSystem] [] [main] - No global configuration found for akka-persistence - check if agent is installed.
[2022-03-01 10:39:14,976] [INFO] [akka.management.internal.HealthChecksImpl] [] [ShoppingCartService-akka.actor.default-dispatcher-15] - Loading readiness checks [(cluster-membership,akka.management.cluster.scaladsl.ClusterMembershipCheck), (sharding,akka.cluster.sharding.ClusterShardingHealthCheck)]
[2022-03-01 10:39:14,976] [INFO] [akka.management.internal.HealthChecksImpl] [] [ShoppingCartService-akka.actor.default-dispatcher-15] - Loading liveness checks []
```

### 2. i am using the same step on my application.

there is the application environment

- base on:  org.springframework.boot:2.0.1.RELEASE
- base on Akka 2.6.14
- base on: scala 2.13

there is same exception when exec java -jar via agent

```log
❯ java -javaagent:/Users/roiocam/Downloads/agent/mesmer-akka-agent.jar -jar path-to-my-jar
Exception in thread "main" java.lang.reflect.InvocationTargetExceptionr -jar path-to-my-jar
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NoClassDefFoundError: com/typesafe/config/ConfigFactory
        at io.scalac.mesmer.agent.Boot$.premain(Boot.scala:23)
        at io.scalac.mesmer.agent.Boot.premain(Boot.scala)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: com.typesafe.config.ConfigFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        ... 8 more
FATAL ERROR in native method: processing of -javaagent failed
[1]    70925 abort      java -javaagent:/Users/roiocam/Downloads/agent/mesmer-akka-agent.jar -jar 

```

**Comment by Roiocam** [comment]
> Let me know if you still get NoClassFound with 0.5.0.

Actually they both unavailable on scala and Java.

The [Lightbend shopping cart service exmaple](https://developer.lightbend.com/docs/akka-platform-guide/microservices-tutorial/projection-grpc-client.html) scala version not working either.

I think they can’t work outside the project. Whether the agent jar is downloaded from a [remote repository](https://mvnrepository.com/artifact/io.scalac/mesmer-akka-agent_2.13/0.5.0) or repackaged by executing the 'sbt agent/assembly' or `package` from the source.

this is scala project log.

```log
 Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.NoClassDefFoundError: io/scalac/mesmer/core/util/LibraryInfo$
        at io.scalac.mesmer.agent.Boot$.premain(Boot.scala:33)
        at io.scalac.mesmer.agent.Boot.premain(Boot.scala)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: io.scalac.mesmer.core.util.LibraryInfo$
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 8 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422

```

I'd love to help fix this issue, but I'm not familiar with the `java agent` or `bytebuddy`, so I'm counting on you guys to fix it.


Best regards

**Comment by Roiocam** [comment]
In fact, they are not available on both scala and Java when executed via "java - jar".

i am using the [same project](https://developer.lightbend.com/docs/akka-platform-guide/microservices-tutorial/projection-grpc-client.html) by scala version. When work that exec `Main.scala` by IDEA. but fail on exec `java -jar`

this is the exception log.

```log
 java -javaagent:/Users/roiocam/Downloads/agent/mesmer-akka-agent.jar -jar target/scala-2.13/shopping-cart-service_2.13-HEAD-20220301-1538.jar
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.NoClassDefFoundError: com/typesafe/config/ConfigFactory
        at io.scalac.mesmer.agent.Boot$.premain(Boot.scala:23)
        at io.scalac.mesmer.agent.Boot.premain(Boot.scala)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: com.typesafe.config.ConfigFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 8 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
[1]    81064 abort      java -javaagent:/Users/roiocam/Downloads/agent/mesmer-akka-agent.jar -jar 

```

**Comment by lgajowy** [comment]
Thanks! That's plenty for me to work on. I will investigate get back to you.

**Comment by lgajowy** [comment]
I was able to run 0.5.0 version with lightbend example after doing some pom.xml tweaks. I observed both cluster and persistence metrics. I think that you have to add the following plugin configuration in order to have an executable jar with proper dependencies on the classpath: 

```xml
 <plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-dependency-plugin</artifactId>
    <executions>
        <execution>
            <id>copy</id>
            <phase>package</phase>
            <goals>
                <goal>copy-dependencies</goal>
            </goals>
            <configuration>
                <outputDirectory>
                    ${project.build.directory}/lib
                </outputDirectory>
            </configuration>
        </execution>
    </executions>
</plugin>
<plugin>
    <!-- Build an executable JAR -->
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-jar-plugin</artifactId>
    <version>3.1.0</version>
    <configuration>
        <archive>
            <manifest>
                <addClasspath>true</addClasspath>
                <classpathPrefix>lib/</classpathPrefix>
                <mainClass>shopping.cart.Main</mainClass>
            </manifest>
        </archive>
    </configuration>
</plugin>
```

After that you can run it like this: 


```
 java -javaagent:mesmer-akka-agent_2.13-0.5.0.jar -Dconfig.resource=local1.conf -jar target/shopping-cart-service-1.0.jar
```

I think the IDE may have a different way of providing the dependencies to the classpath and that's the reason it worked for you. I'm not a maven expert and not sure if this is the only way. LMK if this is helpful.

**Comment by lgajowy** [comment]
Side note: did you see this discussion: https://github.com/ScalaConsultants/mesmer-akka-agent/discussions/272? We're going to migrate to opentelemetry agent in the next release. Depending on your needs, this might be important.

**Comment by Roiocam** [comment]
> Side note: did you see this discussion: #272? We're going to migrate to opentelemetry agent in the next release. Depending on your needs, this might be important.

I didn't notice the discussions, but it was important for me.

In fact I have tried Opentelemetry agent

I will continue to follow this epic.

> I think the IDE may have a different way of providing the dependencies to the classpath and that's the reason it worked for you. I'm not a maven expert and not sure if this is the only way. LMK if this is helpful.

Thank you for taking the trouble to answer this elementary question. 

I think I don't know enough about how Jar packages work. So i tried to unpack to see the diffrence bewteen the basic Lightbend example Jar and the Jar with the plugin, plus the Spring Boot way of packaging jar.

For IDEA Why it works, it load jar from FileSystem. 

For Spring Boot, they dependency jar to the inside of jar, and using they own dependency library path and [ClassLoader](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-tools/spring-boot-loader/src/main/java/org/springframework/boot/loader/LaunchedURLClassLoader.java).

But agent execute before Spring Launched, so they can not using Spring custom ClassLoader load the dependency from `BOOT-INF/lib`, and failure execute on my application.

For `maven-dependency-plugin ` and `maven-jar-plugin`, they using same way as IDEA. 

At the moment, I haven't found a better way to make Agent and Spring Boot work together. 

I think this issue can be closed. your answer solve my issue, and i know why they does not working. Thanks again for your help!

**Comment by lgajowy** [comment]
Glad we could help. Feel free to reach us again anytime. :)
