### ISSUE TITLE
Core class not found: NoClassDefFound  when project does not depend akka-extension 

### ISSUE THREAD

**Issue by lgajowy** [ScalaConsultants/mesmer#375]
```
Exception in thread "main" java.lang.NoClassDefFoundError: io/scalac/mesmer/core/actor/ActorCellMetrics
	at io.scalac.mesmer.otelextension.instrumentations.akka.actor.impl.ActorMetricsInitAdvice$.initializeMetrics(ActorMetricsInitAdvice.scala:16)
	at akka.actor.ActorCell.init(ActorCell.scala:411)
	at akka.actor.LocalActorRef.<init>(ActorRef.scala:361)
	at akka.actor.LocalActorRefProvider$$anon$2.<init>(ActorRefProvider.scala:535)
	at akka.actor.LocalActorRefProvider.rootGuardian$lzycompute(ActorRefProvider.scala:529)
	at akka.actor.LocalActorRefProvider.rootGuardian(ActorRefProvider.scala:528)
	at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:605)
	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:1026)
	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:1022)
	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:1022)
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:1045)
	at akka.actor.typed.ActorSystem$.createInternal(ActorSystem.scala:290)
	at akka.actor.typed.ActorSystem$.apply(ActorSystem.scala:198)
	at com.example.QuickstartApp$.main(QuickstartApp.scala:40)
	at com.example.QuickstartApp.main(QuickstartApp.scala)
Caused by: java.lang.ClassNotFoundException: io.scalac.mesmer.core.actor.ActorCellMetrics
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 15 more
```

This happens when there's no akka-extension in project dependencies. It's not crucial now, because Mesmer currently requires the akka-extension and akka-extension fetches the core module transitively avoiding the error. However, the core should be provided by the otel-extension jar ideally.

**Comment by lgajowy** [comment]
Temp solution would be to just include core in the instrumented application dependency session... But ideally we'd like to not make users do that and just use the extension jar with opentelemetry agent.
