### ISSUE TITLE
Akka Cluster errors in logs for non-clustered app

### ISSUE THREAD

**Issue by jczuchnowski** [ScalaConsultants/mesmer#449]
When added Mesmer to an application that doesn't include Akka Cluster, the logs contain this information:
```
[info] 2022-07-28 14:01:50 ERROR i.s.mesmer.extension.AkkaMonitoring  ActorSystem is not properly configured to start cluster monitor of type ClusterEventsMonitor$
[info] 2022-07-28 14:01:50 DEBUG a.a.t.i.r.LocalReceptionist akka://akkaq1-system/system/localReceptionist Actor was registered: ServiceKey[io.scalac.mesmer.core.event.StreamEvent](io.scalac.metric.stream) Actor[akka://akkaq1-system/system/mesmerStreamMonitor/$$b-adapter#533007682]
[info] 2022-07-28 14:01:50 ERROR i.s.mesmer.extension.AkkaMonitoring  ActorSystem is not properly configured to start cluster monitor of type ClusterRegionsMonitorActor$
[info] 2022-07-28 14:01:50 ERROR i.s.mesmer.extension.AkkaMonitoring  ActorSystem is not properly configured to start cluster monitor of type ClusterSelfNodeEventsActor$
```

**Comment by mBut** [comment]
`sbt new akka/akka-http-quickstart-scala.g8` on run with mesmer agent also throws number of errors

```
[error] Exception in thread "Thread-3" java.lang.NoClassDefFoundError: io/scalac/mesmer/core/util/Retry$
[error]   at io.scalac.mesmer.otelextension.instrumentations.akka.stream.AkkaStreamMonitorExtension$.io$scalac$mesmer$otelextension$instrumentations$akka$stream$AkkaStreamMonitorExtension$$registerWhenSystemIsInitialized(AkkaStreamMonitorExtension.scala:84)
[error]   at io.scalac.mesmer.otelextension.instrumentations.akka.stream.AkkaStreamMonitorExtension$$anon$1.run(AkkaStreamMonitorExtension.scala:80)
[error]   at java.base/java.lang.Thread.run(Thread.java:1589)
[error] Caused by: java.lang.ClassNotFoundException: io.scalac.mesmer.core.util.Retry$
[error]   at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[error]   at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[error]   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[error]   ... 3 more
[error] Exception in thread "main" java.lang.NoClassDefFoundError: akka/cluster/typed/Cluster$
[error]   at io.scalac.mesmer.otelextension.instrumentations.akka.cluster.extension.AkkaClusterMonitorExtension$.registerExtension(AkkaClusterMonitorExtension.scala:63)
[error]   at io.scalac.mesmer.otelextension.instrumentations.akka.cluster.extension.AkkaClusterMonitorExtension.registerExtension(AkkaClusterMonitorExtension.scala)
[error]   at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:799)
[error]   at akka.actor.typed.ActorSystem$.createInternal(ActorSystem.scala:289)
[error]   at akka.actor.typed.ActorSystem$.apply(ActorSystem.scala:198)
[error]   at com.example.QuickstartApp$.main(QuickstartApp.scala:40)
[error]   at com.example.QuickstartApp.main(QuickstartApp.scala)
[error] Caused by: java.lang.ClassNotFoundException: akka.cluster.typed.Cluster$
[error]   at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[error]   at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[error]   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[error]   ... 7 more
```

This project contains only the following dependencies 
```
      "com.typesafe.akka" %% "akka-http"                % akkaHttpVersion,
      "com.typesafe.akka" %% "akka-http-spray-json"     % akkaHttpVersion,
      "com.typesafe.akka" %% "akka-actor-typed"         % akkaVersion,
      "com.typesafe.akka" %% "akka-stream"              % akkaVersion,
```
